services:
  stats-server:
    build: stats/stats-server
    image: stats-server-image
    container_name: stats-server-container
    ports:
      - "9091:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statistics
      - SPRING_DATASOURCE_USERNAME=db_user
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver

  stats-db:
    image: postgres:16.1
    container_name: stats-db-container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=db_user
      - POSTGRES_DB=statistics


#  ewm-service:
#    build: evm-service
#    image: evm-service-image
#    container_name: evm-service-container
#    ports:
#      - "8080:8080"
#    depends_on:
#      - evm-db
#
#  ewm-db:
#    image: postgres:16.1
#    container_name: stats-db-container
#    ports:
#      - "6532:5432"
#    environment:
#      - POSTGRES_PASSWORD=12345
#        - POSTGRES_USER=db_user
#        - POSTGRES_DB=explore_db


